-- MySQL Script generated by MySQL Workbench
-- Wed Apr 26 21:11:06 2023
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema todolistapp
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema todolistapp
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `todolistapp` DEFAULT CHARACTER SET utf8 ;
USE `todolistapp` ;

-- -----------------------------------------------------
-- Table `todolistapp`.`Tasks`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todolistapp`.`Tasks` (
  `idTask` INT NOT NULL AUTO_INCREMENT,
  `name` VARCHAR(25) NULL,
  `description` VARCHAR(45) NULL,
  PRIMARY KEY (`idTask`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `todolistapp`.`Items`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `todolistapp`.`Items` (
  `idItem` INT NOT NULL AUTO_INCREMENT,
  `taskId` INT NULL,
  `name` VARCHAR(25) NULL,
  `description` VARCHAR(45) NULL,
  `isCompleted` SMALLINT NULL,
  PRIMARY KEY (`idItem`),
  INDEX `Fk_Items_Task_Id_idx` (`taskId` ASC) VISIBLE,
  CONSTRAINT `Fk_Items_Task_Id`
    FOREIGN KEY (`taskId`)
    REFERENCES `todolistapp`.`Tasks` (`idTask`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
